# Document:
# http://simiki.org/docs/configuration.html

url: 
title: MANJIA_WIKI
keywords: Hack, Tools
description: 
author: NANJIA

root: /wiki

source: content
destination: output
themes_dir: themes
#theme: 

default_ext: md
pygments: true
debug: false

